# Generated by Django 5.2.8 on 2025-11-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_role_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('restaurant', 'restaurant')], max_length=50, null=True),
        ),
    ]
